# common setting

spring:
  application:
    name: QueryService
  main:
    web-application-type: servlet
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: ${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE:5}
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:20}
      connection-timeout: ${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT:30000}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      timeout: ${SPRING_DATA_REDIS_TIMEOUT:5000}
      lettuce:
        pool:
          max-active: ${SPRING_DATA_REDIS_POOL_MAX_ACTIVE:8}
          max-idle: ${SPRING_DATA_REDIS_POOL_MAX_IDLE:8}
          min-idle: ${SPRING_DATA_REDIS_POOL_MIN_IDLE:0}
          max-wait: ${SPRING_DATA_REDIS_POOL_MAX_WAIT:-1ms}

logging:
  file:
    name: ./logs/query-service.log
  level:
    root: INFO
    org.java.queryservice: DEBUG